<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Авторизация</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/style.css">
    </head>
    <body>
        <div class="container">
            <?php use Phalcon\Tag; ?>

            <div class="row">
                <div class="page-header">
                    <h1>Авторизация</h1>
                </div>
            </div>

            <div class="row">
                <?php echo Tag::form(["id" => "form", "method" => "post", "action" => "/"]); ?>
                <p>
                    <?php $this->flash->output() ?>
                </p>
                <div class="card">
                    <div class="card-body">
                        <p>
                            <label for="login">
                                <svg class="bi bi-person-fill" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M5 16s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H5zm5-6a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path>
                                </svg>
                            </label>
                            <?php echo Tag::textField(["id" => "login", "name" => "login"]) ?>
                        </p>
                        <p>
                            <label for="password">
                                <svg class="bi bi-lock-fill" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <rect width="11" height="9" x="4.5" y="8" rx="2"></rect>
                                    <path fill-rule="evenodd" d="M6.5 5a3.5 3.5 0 117 0v3h-1V5a2.5 2.5 0 00-5 0v3h-1V5z" clip-rule="evenodd"></path>
                                </svg>
                            </label>
                            <?php echo Tag::passwordField(["id" => "password", "name" => "password"]) ?>
                        </p>
                        <p class="text-center">
                            <?php echo Tag::submitButton("Войти") ?>
                        </p>
                    </div>
                </div>
                <p><?php echo Tag::hiddenField(["id" => "csrf", "name" => $this->security->getTokenKey(), "value" => $this->security->getToken()]) ?></p>
                <?php echo Tag::endForm(); ?>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>